### ISSUE TITLE
pronote.json & devoirs.json ne se créent pas !

### ISSUE THREAD

**Issue by CHALENCON-Yoan** [drawbu/drawbot#10]
Bonsoir, j'ai écrit le code et je l'ai extrait dans un dossier.
J'ai fais la commande "pip install -r requirements.txt" dans mon cmd. Le fichier config.json s'est créé et je l'ai modifié avec les données nécessaires, cependant aucun fichier pronote.json ni devoirs.json que se soit dans ce dossier ou dans le sous dossier "app". J'ai bien essayé de lancer les autres fichiers python (bot.py, pronote.py et information.py) mais rien ne se passe : le cmd "travaille" puis me repropose de saisir une commande.

**Comment by drawbu** [comment]
en réalité, il faut lancer le bot via le fichier run.py 😄

**Comment by CHALENCON-Yoan** [comment]
Et comment on fait ça ?

**Comment by drawbu** [comment]
Comme un fichier python normal depuis votre cmd ou depuis votre IDE. `python run.py`

**Comment by CHALENCON-Yoan** [comment]
En faisant ça le fichier config.json se recrée en enlevant le token que j'avais mis et les fichiers pronote.json et devoirs.json n'apparaissent toujours nul part.

**Comment by drawbu** [comment]
Ok tout est expliqué dans le README.md

**Comment by CHALENCON-Yoan** [comment]
Merci !
