### ISSUE TITLE
fichier config.json se regénère à chaque tentative de lancement.

### ISSUE THREAD

**Issue by Ludo-code** [drawbu/drawbot#11]
Bonsoir/Bonjour impossible d'utilisez le bot je suis sous pyhton3.9.6 et à chaque tentative de lancement du bot le fichier config est réécris et il est donc impossible de le lancer.

**Comment by Ludo-code** [comment]
je propose le patch suivant :


```py
import json
import os
from discord.ext import commands


class Bot(commands.Bot):

    def __init__(self):
        """Initialize the bot and load the config for token and prefix."""
        self.embed_color = 0x1E744F
        self._token = None

        if not os.path.isfile('config.json'):
            with open('config.json', 'w') as f:
                json.dump({'token': "null", 'prefix': ';'}, f, indent=4)
            return

        with open('config.json') as f:
            config = json.load(f)

        super().__init__(config.get('prefix', ';'))
        self._token = config.get('token')

        self.remove_command('help')

        for filename in os.listdir("app/cogs"):
            if filename.endswith('.py'):
                self.load_extension(f'app.cogs.{filename[:-3]}')

    def run(self):
        if not self._token:
            print('veuillez indiquer token Discord dans le fichier config.json')
            return

        super().run(self._token)

    async def on_ready(self):
        print(f'Connecté en temps que {self.user.name} !')
```

**Comment by hermitoff** [comment]
Bonsoir, j'ai appliquer votre patch, le problème est résolu pour le config.json.
Mais a la place j'ai ce problème juste après avoir exécuter run.py

```
PS C:\Users\Hermito\Desktop\drawbot> python run.py
Connecté en temps que Mont-Nuka !
Unhandled exception in internal background task 'homeworks_pronote'.
Traceback (most recent call last):
  File "C:\Users\Hermito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\Hermito\Desktop\drawbot\app\cogs\pronote.py", line 52, in homeworks_pronote
    if config_pronote['folderName'] is not None:
KeyError: 'folderName'
```

Le bot est en ligne, mais ne fais rien.

**Comment by Ludo-code** [comment]
> 
> 
> Bonsoir, j'ai appliquer votre patch, le problème est résolu pour le config.json.
> Mais a la place j'ai ce problème juste après avoir exécuter run.py
> 
> ```
> PS C:\Users\Hermito\Desktop\drawbot> python run.py
> Connecté en temps que Mont-Nuka !
> Unhandled exception in internal background task 'homeworks_pronote'.
> Traceback (most recent call last):
>   File "C:\Users\Hermito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
>     await self.coro(*args, **kwargs)
>   File "C:\Users\Hermito\Desktop\drawbot\app\cogs\pronote.py", line 52, in homeworks_pronote
>     if config_pronote['folderName'] is not None:
> KeyError: 'folderName'
> ```
> 
> Le bot est en ligne, mais ne fais rien.

j'ai effectivement patché le fichier de départ mais pas encore le reste comme le fichier pronote.json et devoirs.json le soucis étant que pour devoir.json je ne sais pas comment le générer.

**Comment by Ludo-code** [comment]
si on regarde dans le fichier pronote.py : 
![image](https://user-images.githubusercontent.com/56892223/124092434-23a5a400-da57-11eb-8920-2e124405eff3.png)
on peux voir que c'est le fais qu'il manque le fichier pronote.json qui pause soucis...

Mais que fais le créateur

**Comment by pumarc** [comment]
Bonjour,

je propose le PR #12 pour corriger l'erreur (meme chose que ce que etait proposer plus haut) ;)

**Comment by Ludo-code** [comment]
On peux donc Close cette issue.
