### ISSUE TITLE
pronotepy.PronoteAPIError

### ISSUE THREAD

**Issue by Bolobos** [drawbu/drawbot#15]
Bonjour,
J'ai l'erreur `Connexion à Pronote échoué` . Après un test, je vois que cela viens de cette partie du code :
```
        except pronotepy.PronoteAPIError:
            print("Connexion à Pronote échoué")
            return
```
Comment résoudre ce problème ? Cela viens surement pronotepy mais je ne suis sur de rien.

Merci, bonne journée !

**Comment by alexixi** [comment]
Bonjour, cette partie du code se déclenche lorsque pronotepy n'arrive pas à se connecter à un compte Pronote. Il se peut que l'identifiant, le mot de passe ou encore l'url de connexion que vous avez rentré soient erronés.

**Comment by Bolobos** [comment]
A ok merci. J'ai une adresse comme cela :    ` "url": "https://0741532n.index-education.net/pronote/eleve.html"` 
Pour les identifiants je pense que c'est bon mais malheureusement je ne peux pas réessayer psq pronote est down pendant les vacances. Je verrais ça la rentrée prochaine.
Merci !
