### ISSUE TITLE
How can we deploy this in a docker container ?

### ISSUE THREAD

**Issue by Wans22** [drawbu/drawbot#27]
Hi, how can we deploy this project in a docker container?
I would like to do this to run it easily 24h/24.
I tried to do it by myself but I am not very competent 😆 
Thank you in advance for your answer!

**Comment by drawbu** [comment]
It does not have been implemented yet, but that's a very good idea!

**Comment by drawbu** [comment]
So, check out the latest release @Wans22, its done!
